### ISSUE TITLE
Confusing result on wrong input

### ISSUE THREAD

**Issue by jsjohann** [perezdev/Accio#105]
If I type a wrong command like "=" instead of ":", the search takes a while and then displays all the cards of the database. I guess it would be better to show "no cards found" or to recognize the wrong input and display a list of the correct commands.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3832460/88791667-63567280-d19a-11ea-917e-c1c17ba8cb0b.png">

**Comment by perezdev** [comment]
This should be fixed in test now: http://test.accio.cards/Search?searchText=cn=3&sortBy=sn&sortOrder=asc&cardView=images
