### ISSUE TITLE
Link name of artist to search query showing all cards of this artist

### ISSUE THREAD

**Issue by jsjohann** [perezdev/Accio#107]
It would be nice to be able to click on the already highlighted artist name on the detail page of the card and then be taken to a search query showing all the cards of this artist.

1)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3832460/88792810-24292100-d19c-11ea-8b4d-6002385ab4e8.png">

2)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3832460/88792836-3014e300-d19c-11ea-9b0c-e5e8f136df2b.png">

**Comment by Tressley** [comment]
For cards that have two artists, each artist's name should be an individual query. Right now it queries both artist names. See: http://accio.cards/Card?cardId=02f77dad-322c-4448-a71b-1b243c8cb348

**Comment by perezdev** [comment]
I'm splitting this issue into a separate issue. The functionality for this request is complete. A new request has been created to track splitting the artist into two.
