### ISSUE TITLE
Advanced Search for "Broom"

### ISSUE THREAD

**Issue by vdsams** [perezdev/Accio#132]
When I type "broom" in the "keyword" box in advanced search, Accio returns 9 random cards (the same 9 every time).

**Comment by perezdev** [comment]
I don't think keywords are hooked into the query. I'll take a look. Thanks, Sammy.

**Comment by perezdev** [comment]
This is similar to #130 and is fixed in fe541f7dcb082315dc8764029d5af03c1747d646
