### ISSUE TITLE
Create login page design

### ISSUE THREAD

**Issue by perezdev** [perezdev/Accio#143]
This is just the Zeplin design. I designed the current system to require an email and a username. It would be good if we could get designs for the following items related to authentication:

- login page
- password reset logged out and logged in
- user account icon logged out and logged in

**Comment by Tressley** [comment]
**Register:** https://zpl.io/25Q9Ege, https://zpl.io/aM6ndq3
**Log in:** https://zpl.io/bP6nq4D, https://zpl.io/blGAlpv
